pipeline {
    // These are pre-build section
    agent {
        node {
            label 'AGENT-1'
        }
    }

    environment {
      COURSE = "Jenkins"
    }

        options {
        timeout(time: 60, unit: 'MINUTES') 
        disableConcurrentBuilds()
        ansiColor('xterm')
    }

    // parameters {
    //     string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
    //     text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')
    //     booleanParam(name: 'DEPLOY', defaultValue: false, description: 'Toggle this value')
    //     choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')
    //     password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
    // }

     // This is build section
     stages{
        stage('Init'){
            steps{
                script {
                    withAWS(region:'us-east-1',credentials:'aws-creds') {
                    sh """
                    cd 00-vpc 
                    terraform init 

                    """
                    }
                }
           
            }
        }
        stage('Plan'){
            steps{
                script {
                    withAWS(region:'us-east-1',credentials:'aws-creds') {
                    sh """
                    cd 00-vpc 
                    terraform plan

                    """
                    }
                }
                
            }
        }
        stage('Apply'){
            steps{
                script {
                    withAWS(region:'us-east-1',credentials:'aws-creds') {
                        sh """
                            cd 00-vpc
                            terraform apply -auto-approve
                        """
                    }

                }
                
            }
        }

        stage ('Trigger SG'){
            steps{
                script {
                    build job: '10-sg';
                    wait: true, // Wait for completion
                    propagate: true // Propagate status

                }
            }
        }
     }
     // This is post-build section
     post {
        always{
            echo 'I will always say Hello again!'
        }
        success{
            echo 'I will run if pipeline success'
        }
        failure{
            echo 'I will run if pipeline failure'
        }
     }
}